stages:
  - build

variables:
  PYTHONUNBUFFERED: "1"
  DRAKE_DEBUG_BACKTRACE: "1"

x86_64-centos6-gcc4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - scl enable devtoolset-4 rh-python34 "farm/configure --arch x86_64 --os centos6 --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install"
    - cd ../elle-build && scl enable devtoolset-4 rh-python34 "python3 drake -j 4 //build"
    - cd ../elle-build && scl enable devtoolset-4 rh-python34 "python3 drake -j 4 //check"
    - cd ../elle-build && scl enable devtoolset-4 rh-python34 "python3 drake -j 4 //install"
    - TARBALL=elle-x86_64-centos6-gcc4-$(GIT_DIR=../elle/.git git describe).tbz
    - tar -cvjf ../$TARBALL -C ../elle-install . --show-transformed-names --transform "s,^\\./,elle-$(GIT_DIR=../elle/.git git describe)/,"
    - scp ../$TARBALL debian@debian.infinit.io:/tmp
  tags:
    - x86_64
    - centos6
    - gcc4

x86_64-ubuntu-gcc4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os trusty --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - export ELLE_LOG_CHECK_FORMATS=1
    - cd ../elle-build && python3 drake -j $(nproc) //build
    - cd ../elle-build && python3 drake -j $(($(nproc) / 4)) //check
    - cd ../elle-build && python3 drake -j $(nproc) //install
  tags:
    - x86_64
    - ubuntu
    - gcc4

x86_64-jessie-gcc4:
  stage: build
  script:
    - time ./buildenv --cleanup-build-trees --build-trees-root "/cache/$CI_PROJECT_NAME"  --verbose
    - git submodule update --init --recursive
    - git fetch origin --tags
    - SOURCE_DIR="${CI_PROJECT_DIR}"
    - BUILD_DIR="$(dirname ${CI_PROJECT_DIR})/${CI_PROJECT_NAME}-build"
    - INSTALL_DIR="${SOURCE_DIR}/_install"
    - DESC=$(git describe)
    - time ./buildenv --pick-build-tree --branch "$CI_BUILD_REF_NAME" --link-build-tree "$BUILD_DIR" --build-trees-root "/cache/$CI_PROJECT_NAME"
    - time ./buildenv --cache-download-build-tree --exclude='*.deb,*.rpm' --branch "$CI_BUILD_REF_NAME" --build-trees-root "/cache/$CI_PROJECT_NAME" --cache-namespace "$CI_RUNNER_DESCRIPTION/$CI_PROJECT_NAME" --cache-id "$CI_RUNNER_ID" --verbose
    - mkdir -p "$INSTALL_DIR"
    - farm/configure --arch x86_64 --os jessie --compiler gcc4 --project Elle --source-dir . --build-dir "$BUILD_DIR" --install-dir "$INSTALL_DIR"
    - cd "$BUILD_DIR"
    - python3 drake -j 4 //build
    - python3 drake -j 4 //check
    - python3 drake -j 4 //install
    - TARBALL="$BUILD_DIR/elle-x86_64-jessie-gcc4-$DESC.tbz"
    - tar -cvjf "$TARBALL" -C "$INSTALL_DIR" . --show-transformed-names --transform "s,^\\./,elle-$DESC/,"
    - scp "$TARBALL" debian@debian.infinit.io:/tmp
    - cd "$SOURCE_DIR"
    - time ./buildenv --cache-upload-build-tree --exclude='*.deb,*.rpm' --branch "$CI_BUILD_REF_NAME" --build-trees-root "/cache/$CI_PROJECT_NAME" --cache-namespace "$CI_RUNNER_DESCRIPTION/$CI_PROJECT_NAME" --cache-id "$CI_RUNNER_ID" --verbose
  tags:
    - x86_64
    - jessie
    - gcc4

i386-jessie-gcc4:
  stage: build
  script:
    - time ./buildenv --cleanup-build-trees --build-trees-root "/cache/$CI_PROJECT_NAME"  --verbose
    - git submodule update --init --recursive
    - git fetch origin --tags
    - SOURCE_DIR="${CI_PROJECT_DIR}"
    - BUILD_DIR="$(dirname ${CI_PROJECT_DIR})/${CI_PROJECT_NAME}-build"
    - INSTALL_DIR="${SOURCE_DIR}/_install"
    - DESC=$(git describe)
    - time ./buildenv --pick-build-tree --branch "$CI_BUILD_REF_NAME" --link-build-tree "$BUILD_DIR" --build-trees-root "/cache/$CI_PROJECT_NAME"
    - time ./buildenv --cache-download-build-tree --exclude='*.deb,*.rpm' --branch "$CI_BUILD_REF_NAME" --build-trees-root "/cache/$CI_PROJECT_NAME" --cache-namespace "$CI_RUNNER_DESCRIPTION/$CI_PROJECT_NAME" --cache-id "$CI_RUNNER_ID" --verbose
    - mkdir -p "$INSTALL_DIR"
    - farm/configure --arch i386 --os jessie --compiler gcc4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
    - TARBALL="$BUILD_DIR/elle-i386-jessie-gcc4-$DESC.tbz"
    - tar -cvjf "$TARBALL" -C "$INSTALL_DIR" . --show-transformed-names --transform "s,^\\./,elle-$DESC/,"
    - scp "$TARBALL" debian@debian.infinit.io:/tmp
    - cd "$SOURCE_DIR"
    - time ./buildenv --cache-upload-build-tree --exclude='*.deb,*.rpm' --branch "$CI_BUILD_REF_NAME" --build-trees-root "/cache/$CI_PROJECT_NAME" --cache-namespace "$CI_RUNNER_DESCRIPTION/$CI_PROJECT_NAME" --cache-id "$CI_RUNNER_ID" --verbose
  tags:
    - i386
    - jessie
    - gcc4

x86_64-windows-mingw4:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os windows --compiler mingw4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
  tags:
    - x86_64
    - windows
    - mingw4

#i686-windows-mingw4:
#  stage: build
#  script:
#    - git submodule update --init --recursive
#    - git fetch origin --tags
#    - mkdir -p ../elle-build ../elle-install
#    - farm/configure --arch i686 --os windows --compiler mingw4 --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
#    - cd ../elle-build && python3 drake -j 4 //build
#    - cd ../elle-build && python3 drake -j 4 //check
#    - cd ../elle-build && python3 drake -j 4 //install
#  tags:
#    - i686
#    - windows
#    - mingw4

x86_64-osx-clang:
  stage: build
  script:
    - git submodule update --init --recursive
    - git fetch origin --tags
    - mkdir -p ../elle-build ../elle-install
    - farm/configure --arch x86_64 --os osx --compiler clang --project Elle --source-dir . --build-dir ../elle-build --install-dir ../elle-install
    - cd ../elle-build && python3 drake -j 4 //build
    - cd ../elle-build && python3 drake -j 4 //check
    - cd ../elle-build && python3 drake -j 4 //install
    - TARBALL=elle-x86_64-osx-clang3-$(GIT_DIR=../elle/.git git describe).tbz
    - gtar -cvjf ../$TARBALL -C ../elle-install . --show-transformed-names --transform "s,^\\./,elle-$(GIT_DIR=../elle/.git git describe)/,"
    - scp ../$TARBALL debian@debian.infinit.io:/tmp
  tags:
    - x86_64
    - osx
    - clang
